
package soap.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "AccionInvalida", targetNamespace = "http://localhost:8280/transportista-web/webservice/nodoCentral")
public class AccionInvalida_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private AccionInvalida faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public AccionInvalida_Exception(String message, AccionInvalida faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public AccionInvalida_Exception(String message, AccionInvalida faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: soap.client.AccionInvalida
     */
    public AccionInvalida getFaultInfo() {
        return faultInfo;
    }

}
