
package soap.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "nodoCentral", targetNamespace = "http://localhost:8280/transportista-web/webservice/nodoCentral")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NodoCentral {


    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws AccionInvalida_Exception
     */
    @WebMethod(action = "listar")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "informarTodosEstadoLoteDosis", targetNamespace = "http://localhost:8280/transportista-web/webservice/nodoCentral", className = "soap.client.InformarTodosEstadoLoteDosis")
    @ResponseWrapper(localName = "informarTodosEstadoLoteDosisResponse", targetNamespace = "http://localhost:8280/transportista-web/webservice/nodoCentral", className = "soap.client.InformarTodosEstadoLoteDosisResponse")
    public List<String> informarTodosEstadoLoteDosis()
        throws AccionInvalida_Exception
    ;

    /**
     * 
     * @param idVacunatorio
     * @param idVacuna
     * @param idLote
     * @return
     *     returns java.lang.String
     * @throws AccionInvalida_Exception
     */
    @WebMethod(action = "obtener")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "informarEstadoLoteDosis", targetNamespace = "http://localhost:8280/transportista-web/webservice/nodoCentral", className = "soap.client.InformarEstadoLoteDosis")
    @ResponseWrapper(localName = "informarEstadoLoteDosisResponse", targetNamespace = "http://localhost:8280/transportista-web/webservice/nodoCentral", className = "soap.client.InformarEstadoLoteDosisResponse")
    public String informarEstadoLoteDosis(
        @WebParam(name = "idLote", targetNamespace = "")
        String idLote,
        @WebParam(name = "idVacunatorio", targetNamespace = "")
        String idVacunatorio,
        @WebParam(name = "idVacuna", targetNamespace = "")
        String idVacuna)
        throws AccionInvalida_Exception
    ;

    /**
     * 
     * @param cantidadTotal
     * @param idVacunatorio
     * @param idVacuna
     * @param idLote
     * @return
     *     returns java.lang.String
     * @throws AccionInvalida_Exception
     */
    @WebMethod(action = "agregar")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "recibirNuevoLote", targetNamespace = "http://localhost:8280/transportista-web/webservice/nodoCentral", className = "soap.client.RecibirNuevoLote")
    @ResponseWrapper(localName = "recibirNuevoLoteResponse", targetNamespace = "http://localhost:8280/transportista-web/webservice/nodoCentral", className = "soap.client.RecibirNuevoLoteResponse")
    public String recibirNuevoLote(
        @WebParam(name = "idLote", targetNamespace = "")
        String idLote,
        @WebParam(name = "idVacunatorio", targetNamespace = "")
        String idVacunatorio,
        @WebParam(name = "idVacuna", targetNamespace = "")
        String idVacuna,
        @WebParam(name = "cantidadTotal", targetNamespace = "")
        String cantidadTotal)
        throws AccionInvalida_Exception
    ;

}
